routes/admin.php
<?php
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('perms','PermissionController');
});

routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    public function index()
    {
        $perms = Permission::all();
        return view('admin.permissions.index', compact('perms'));
    }

    public function create()
    {
        $permissions = Permission::all();
        return view('admin.permissions.create', compact('permissions'));
    }

    public function store(Request $request)
    {
        try {
            $permission = Permission::create($request->all());
        } catch (\Error $error) {
            return redirect()->back()->withInput($request->all());
        }
        \Session::flash('success', "Perm $permission->name was created successfully");
        return redirect()->route('perms.index');
    }

    public function edit($id)
    {
        $permission = Permission::where('id', $id)->first();
        $permissions = Permission::all();

//        dd($permission, $permissions);
        return view('admin.permissions.edit', compact('permissions', 'permission'));
    }

    public function update(Request $request)
    {

    }

}

resources/views/admin/permissions/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Create New Permission</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('perms.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="container">
        <div class="row">
            <div class="col-6">
                {{Form::open(['url' => route('perms.store'), 'method' => 'POST'])}}
                @csrf
                <div class="form-group">
                    {{Form::label('name','Name')}}
                    {{Form::text('name',$permission->name??'',['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::submit('Send',['class'=>'btn btn-success'])}}
                </div>
                {{Form::close()}}
            </div>
            <div class="col-6">
                <div class="list-group">
                    @foreach ($permissions as $permission)
                        <a href="#" class="list-group-item list-group-item-action">
                            {{$permission->name}}
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Create New Permission</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('perms.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="container">
        <div class="row">
            <div class="col-6">
                {{Form::open(['url' => route('perms.update',$permission->id), 'method' => 'POST'])}}
                @csrf
                <div class="form-group">
                    {{Form::label('name','Name')}}
                    {{Form::text('name',$permission->name??'',['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::submit('Send',['class'=>'btn btn-success'])}}
                </div>
                {{Form::close()}}
            </div>
            <div class="col-6">
                <div class="list-group">
                    @foreach ($permissions as $permission)
                        <a href="#" class="list-group-item list-group-item-action">
                            {{$permission->name}}
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/permissions/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Permission Management</h2>
            </div>
            <div class="pull-right">
                @can('perms-create')
                    <a class="btn btn-success" href="{{ route('perms.create') }}"> Create New Permission</a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($perms as $perm)
            <tr>
                <th>{{$perm->id}}</th>
                <td>{{$perm->name}}</td>
                <td>
                    <a class="btn btn-info" href="{{ route('perms.show',$perm->id) }}">Show</a>
                    @can('perms-edit')
                        <a class="btn btn-warning" href="{{ route('perms.edit',$perm->id) }}">Edit</a>
                    @endcan
                    @can('perms-delete')
                        {!! Form::open(['method' => 'DELETE','route' => ['perms.destroy', $perm->id],'style'=>'display:inline']) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}
                    @endcan
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>



@endsection